---
title: "Cover letter"
output: html_document
date: "`r format(Sys.time(), '%Y, %B %d')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Editorial Board
Bioinformatics


We wish to submit the article 'nuccomp: rapidly summarize the contents of FASTA and FASTQ files containing nucleotides' for publication in the journal Bioinformatics.
The software nuccomp rapidly summarizes the contents of biological sequence data in the FASTA and FASTQ formats.
Currently, projects ranging from genome announcements to pangenomic projects rely on the management of sequence data in the FASTA and FASTQ formats making this task essential to this work.
Our software accomplishes this task rapidly and summarizes this information graphically in a high level language, R, which we hope will encourage learning of the implemented methods as well as customization by the end user.
Please consider this manuscript for review in your journal Bioinformatics.


We confirm that this work is original and has not been published elsewhere, and is not currently being considered for publication elsewhere.

We have no conflicts of interest to disclose.

Thank you for considering this manuscript,

Brian J. Knaus, Ph.D.    
Faculty Research Associate    
brian.knaus@oregonstate.edu    

and

Kelly J. Vining, Ph.D.    
Associate Professor    
Kelly.Vining@oregonstate.edu    

Department of Horticulture    
Oregon State University    
4017 Agriculture and Life Sciences Building    
Corvallis, OR 97331    



